In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [6]:
type(list_),type(array_list)

(list, numpy.ndarray)

In [ ]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list.

The list_ variable is a Python list, which is a built-in data structure that can contain a collection
of different types of objects such as integers, strings, and so on.

The array_list variable is a NumPy array, which is a type of homogeneous array that can only contain
elements of the same data type. In this case, since all 
the elements of the list are strings, the NumPy array will also contain strings.

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

for elem in list_:
    print(type(elem))
    
for elem in array_list:
    print(type(elem))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [8]:
# Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

for elem in num_list:
    print(type(elem))
    
for elem in array_list:
    print(type(elem))
    
    # Yes, there will be a difference in the data type of the elements present in list_ and array_list if
    # we change the dtype of array_list to int. The elements in list_ are strings, 
    # while the elements in array_list will be integers.

<class 'list'>
<class 'list'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [13]:
import numpy as np

num_array = np.array([[1,2,3], [4,5,6],[7,8,9]])
shape = num_array.shape
size = num_array.size
shape 


(3, 3)

In [14]:
size


9

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [19]:
arr = np.zeros([3,3])

In [22]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr.size

9

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
import numpy.matlib as nm 

In [26]:
arr1 = nm.ones([5,5])

In [27]:
arr1

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [28]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])